currency:
  url: https://api.apilayer.com/fixer/convert
  api_key: PZgoyB7LALgEpDwopDXQyHYeTW14rrK1
server:
  port: 6666

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter
keycloak:
  realm: Software
  auth-server-url: http://192.168.1.203:8081
  autodetect-bearer-only: true
  ssl-required: none
  resource: backend
#    autodetect-bearer-only: true
  credentials:
    secret: g5Aybp0sCbL3kXeHnoFzv16wdRZq5AXe
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN

      security-collections:
        - name: SERVICIOS DEL ADMINISTRADOR
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/currency/*
    - auth-roles:
        - USER
      security-collections:
        - name: SERVICIOS DE USER
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/currency/*
